 #this is made for nerd font use
 [time]
disabled = false
 format = 'ğŸ•™[\[ $time \]]($style) '
 time_format = "%T"

 [directory]
truncation_length = 5
format = "ğŸ“[$path]($style)[$lock_symbol]($lock_style) "
style = "bold #f57800"
read_only = "ğŸ”’"
read_only_style= "bold white"

 [battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "<U+26A1>"

 [[battery.display]]
threshold = 30
 style = "bold red"

error_symbol = "[<U+2716>](bold red) "

 [cmd_duration]
 min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " [$duration]($style)"

 [git_branch]
 format = " [$symbol$branch]($style) "
 symbol = "ğŸ£ "
 style = "bold yellow"

 [git_commit]
commit_hash_length = 8
 style = "bold white"

 [git_status]
conflicted = "<U+2694><U+FE0F> "
 ahead = "ğŸ <U+FE0F> ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
 untracked = "ğŸ›¤ <U+FE0F>  Ã—${count}"
 stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count}"
 staged = "ğŸ—ƒ <U+FE0F>  Ã—${count}"
 renamed = "ğŸ“› Ã—${count}"
 deleted = "ğŸ—‘ <U+FE0F>  Ã—${count}"
 style = "bright-white"
 format = "$all_status$ahead_behind"

 [hostname]
 ssh_only = false
 format = "[$hostname ]($style)"

style = "bold yellow"
disabled = false

[package]
disabled = true


 [username]
style_user = "green"
 show_always = false
